
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabriel
 */
public class ConfirmarTransferencia extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmarTransferencia
     */
    public ConfirmarTransferencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirmar Tranferência");

        if (Integer.parseInt(Transferir.conta1.getText()) == GabrielBancoPrincipal.conta.getNumero())
        {
            if(Integer.parseInt(Transferir.conta2.getText()) == CriarContaPoupanca.contaPoup.getNumero())
            {
                jLabel1.setText(GabrielBancoPrincipal.conta.getNome() + " deseja transferir " + Transferir.valor.getText() + " para " + CriarContaPoupanca.contaPoup.getNome() + "?");
            }
            if(Integer.parseInt(Transferir.conta2.getText()) == CriarContaEspecial.contaEsp.getNumero())
            {
                jLabel1.setText(GabrielBancoPrincipal.conta.getNome() + " deseja transferir " + Transferir.valor.getText() + " para " + CriarContaEspecial.contaEsp.getNome() + "?");
            }
        }

        else
        {
            if(Integer.parseInt(Transferir.conta1.getText()) == CriarContaPoupanca.contaPoup.getNumero())
            {
                if(Integer.parseInt(Transferir.conta2.getText()) == CriarContaEspecial.contaEsp.getNumero())
                {
                    jLabel1.setText(CriarContaPoupanca.contaPoup.getNome() + " deseja transferir " + Transferir.valor.getText() + " para " + CriarContaEspecial.contaEsp.getNome() + "?");
                }

                if(Integer.parseInt(Transferir.conta2.getText()) == GabrielBancoPrincipal.conta.getNumero())
                {
                    jLabel1.setText(CriarContaPoupanca.contaPoup.getNome() + " deseja transferir " + Transferir.valor.getText() + " para " + GabrielBancoPrincipal.conta.getNome() + "?");
                }
            }

            if(Integer.parseInt(Transferir.conta1.getText()) == CriarContaEspecial.contaEsp.getNumero())
            {
                if(Integer.parseInt(Transferir.conta2.getText()) == CriarContaPoupanca.contaPoup.getNumero())
                {
                    jLabel1.setText(CriarContaEspecial.contaEsp.getNome() + " deseja transferir " + Transferir.valor.getText() + " para " + CriarContaPoupanca.contaPoup.getNome() + "?");
                }
                if(Integer.parseInt(Transferir.conta2.getText()) == GabrielBancoPrincipal.conta.getNumero())
                {
                    jLabel1.setText(CriarContaEspecial.contaEsp.getNome() + " deseja transferir " + Transferir.valor.getText() + " para " + GabrielBancoPrincipal.conta.getNome() + "?");
                }
            }
        }

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 157, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Operação realizada com sucesso!!");
        new Transferir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Integer.parseInt(Transferir.conta1.getText()) == GabrielBancoPrincipal.conta.getNumero())
        {
           if(Integer.parseInt(Transferir.conta2.getText()) == CriarContaPoupanca.contaPoup.getNumero())
           {
               GabrielBancoPrincipal.conta.transferir(GabrielBancoPrincipal.conta, CriarContaPoupanca.contaPoup, Double.parseDouble(Transferir.valor.getText()));
           }
           if(Integer.parseInt(Transferir.conta2.getText()) == CriarContaEspecial.contaEsp.getNumero())
           {
               GabrielBancoPrincipal.conta.transferir(GabrielBancoPrincipal.conta, CriarContaEspecial.contaEsp, Double.parseDouble(Transferir.valor.getText()));
           }
        }
        else
        {
            if(Integer.parseInt(Transferir.conta1.getText()) == CriarContaPoupanca.contaPoup.getNumero())
            {
                if(Integer.parseInt(Transferir.conta2.getText()) == GabrielBancoPrincipal.conta.getNumero())
                {
                    CriarContaPoupanca.contaPoup.transferir(CriarContaPoupanca.contaPoup, GabrielBancoPrincipal.conta, Double.parseDouble(Transferir.valor.getText()));
                }
                if(Integer.parseInt(Transferir.conta2.getText()) == CriarContaEspecial.contaEsp.getNumero())
                {
                    CriarContaPoupanca.contaPoup.transferir(CriarContaPoupanca.contaPoup, CriarContaEspecial.contaEsp, Double.parseDouble(Transferir.valor.getText()));
                }
            }
            else
            {
                if(Integer.parseInt(Transferir.conta1.getText()) == CriarContaEspecial.contaEsp.getNumero())
                {
                    if(Integer.parseInt(Transferir.conta2.getText()) == GabrielBancoPrincipal.conta.getNumero())
                    {
                        CriarContaEspecial.contaEsp.transferir(CriarContaEspecial.contaEsp, GabrielBancoPrincipal.conta, Double.parseDouble(Transferir.valor.getText()));
                    }
                    if(Integer.parseInt(Transferir.conta2.getText()) == CriarContaPoupanca.contaPoup.getNumero())
                    {
                        CriarContaEspecial.contaEsp.transferir(CriarContaEspecial.contaEsp, CriarContaPoupanca.contaPoup, Double.parseDouble(Transferir.valor.getText()));
                    }
                }
            }
        }
        
        JOptionPane.showMessageDialog(null, "Operação realizada com sucesso!!");
        new Transferir().dispose();
        new Operacoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarTransferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
